### ISSUE TITLE
[Enhancement] Reliant on promises... which aren't fully supported in browsers that need polyfills (IE)

### ISSUE THREAD

**Issue by willstocks-tech** [willstocks-tech/dynamically-polyfill-features-for-a-script#1]
Polyfill promises before polyfilling the polyfills?

POLYFILL-CEPTION.

The polyfills we need to load are currently based on promises, which has fairly wide support (https://caniuse.com/#search=promise), except for IE11 and older versions of IE. Chances are, these are the browsers we'll want to be polyfilling functionality for, but can't because promises aren't supported.

Find a way to polyfill promises before running everything else... and without `promise.then()`

**Comment by willstocks-tech** [comment]
There's a way to do this for non-CDN usage... if the script is being self-hosted, the below can be used AFTER the inclusion of the dynamic polyfill script:
`<script src="https://alink.to/promisepolyfill.js" onload="dynamicPolyfill([featuresarray], 'scripttouseURL', 'scriptfunctiontouse()', false></script>`

**Comment by willstocks-tech** [comment]
`callback` function??? Or the following _dirty_ approach?

```
function dynamicPolyfill (features, scriptURL, initFunction) {
	var polyfillFeatures = features;
	var scriptToPolyfill = scriptURL;
	var functionToRunonLoad = initFunction;
	if(typeof Promise !== "undefined") {
		return pageLoaded(polyfillFeatures, scriptToPolyfill, functionToRunonLoad);
	} else {
		console.warn("Promises not supported. Loading polyfill.");
		var promPol = document.createElement('script');
		promPol.src = ('https://polyfill.io/v3/polyfill.min.js?features=Promise');
		document.body.appendChild(promPol);
		polyfill.onerror = function(response) {
			console.error("Could not load Promise polyfill", response);
		} 
		polyfill.onload = function() {
			return pageLoaded(polyfillFeatures, scriptToPolyfill, functionToRunonLoad);
		}
	}
}
```

**Comment by willstocks-tech** [comment]
@MilesZew mentioned in PR https://github.com/willstocks-tech/dynamically-polyfill-features-for-a-script/pull/15#issuecomment-462821432:
> I am currently working on a promise polyfill incase you were planning on working on it.

Once confirmed, this issue will be assigned to him

**Comment by MilesZew** [comment]
Here is the unfinished file (for the Promise polyfill)
[Polyfill.zip](https://github.com/willstocks-tech/dynamically-polyfill-features-for-a-script/files/2861227/Polyfill.zip)

**Comment by willstocks-tech** [comment]
Had a thought - rather than include an inline polyfill for promises, why not just check for native support first (I’m on mobile, so this is syntactically incorrect!):

```
if(Promise) { //check if natively supported
checkPolyfill(p1, p2, p3)
} else {
promifill(p1, p2, p3)
}

function promifill(p1, p2, p3) {
//polyfill promise here using polyfill.io
promifillScript.onload = function(p1, p2, p3) {
checkPolyfill(p1, p2, p3)
}
```

**Comment by willstocks-tech** [comment]
Changing milestone to v0.0.6 as this has now been catered for in PR #19
